---
extends: default

yaml-files:
  - '*.yaml'
  - '*.yml'

rules:
  truthy: disable
  # 80 chars should be enough, but don't fail if a line is longer
  line-length: disable
  # TODO: delete this ignore rule when ci for source code will be enabled
  comments-indentation:
    ignore: |
      .github/workflows/ci.yaml
